CREATE DATABASE mytest2;
use mytest2


CREATE TABLE games
(yr   INT NOT NULL PRIMARY KEY
,city VARCHAR(20)
);
INSERT INTO games(yr,city) VALUES (2004,'Athens');
INSERT INTO games(yr,city) VALUES (2008,'Beijing');
INSERT INTO games(yr,city) VALUES (2012,'London');
SELECT * FROM games;

CREATE VIEW og AS
SELECT yr,city FROM games WHERE yr<2006;
SELECT * FROM og;

CREATE INDEX gamesIdx ON games(city,yr);
SELECT yr, city FROM games

SHOW DATABASES;

DROP DATABASE sys;

CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

SELECT * FROM CUSTOMERS;

 SELECT ID, NAME FROM CUSTOMERS;
 
INSERT INTO CUSTOMERS 
VALUES (7, 'Reemy', 24, 'Odisha', 20000.00 );

 SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE NAME = 'Hardik';
 
 SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 AND age < 25;
 SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 OR age < 25;
 UPDATE CUSTOMERS SET NAME = 'RIKKY' WHERE ID = 6;
 UPDATE CUSTOMERS SET AGE = 25 WHERE ID = 6;
 SELECT * FROM CUSTOMERS;
 DELETE FROM CUSTOMERS WHERE ID = 6;
 DELETE FROM CUSTOMERS
 SELECT * FROM CUSTOMERS WHERE SALARY LIKE '200%';
SELECT * FROM CUSTOMERS LIMIT 4;
SELECT * FROM CUSTOMERS ORDER BY NAME, SALARY;
SELECT * FROM CUSTOMERS ORDER BY NAME DESC;
SELECT NAME, SUM(SALARY) FROM CUSTOMERS GROUP BY NAME;
SELECT SALARY FROM CUSTOMERS ORDER BY SALARY;
SELECT AGE FROM CUSTOMERS ORDER BY AGE;
SELECT AGE,SALARY FROM CUSTOMERS ORDER BY AGE,SALARY;
SELECT DISTINCT SALARY FROM CUSTOMERS ORDER BY SALARY;
SELECT * FROM CUSTOMERS ORDER BY NAME, SALARY;
SELECT * FROM CUSTOMERS ORDER BY NAME DESC;

SELECT * FROM CUSTOMERS
   ORDER BY (CASE ADDRESS
   WHEN 'DELHI' 	 THEN 1
   WHEN 'BHOPAL' 	 THEN 2
   WHEN 'KOTA' 	 THEN 3
   WHEN 'AHMEDABAD' THEN 4
   WHEN 'MP' 	THEN 5
   ELSE 100 END) ASC, ADDRESS DESC;
   
